# Generated by Django 4.1.3 on 2023-01-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="age",
            field=models.CharField(default=20, max_length=3),
            preserve_default=False,
        ),
    ]
