# Generated by Django 4.1.3 on 2023-01-15 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_candidate_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="phone",
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
